### ISSUE TITLE
Recipe by Cuisine does not take into consideration the number of recipes

### ISSUE THREAD

**Issue by SambhaviPD** [SambhaviPD/your-recipebuddy#4]
On bringing up the application in your local,

1. Goto your browser and enter http://localhost:8501
2. Choose the menu item "Recipe by Cuisine"
3. On the page that loads, choose values from dropdown
4. Choose the number of recipes
5. Submit

Output observed: Irrespective of how many number of recipes are chosen, only 1 is returned. 
Expected output: It should return 'x' number of recipes if 'x' is chosen by the user

**Comment by casnes** [comment]
Hey, I just created a fork to fix this issue - are you getting a JSON decode error on your end?

**Comment by SambhaviPD** [comment]
> Hey, I just created a fork to fix this issue - are you getting a JSON decode error on your end?

@casnes - I just changed the menu option to "Recipe by Cuisine" in the title. No json decode error, just that it returns 1 recipe even if we choose any number other than 1.

I'm working on updating the README file. I' adding more information from a local setup perspective on top of a demo link.

**Comment by SambhaviPD** [comment]
@casnes - README is updated now. You should be able to bring up the environment without any hassles. Let know if you face any.

**Comment by SambhaviPD** [comment]
@casnes - I'm working on this issue. If you are interested, you can pick up other issues with `good first issue` label or just about anything that picks your eye.
